# whoever is at the bottom wins

# colorful blue and orange
#COLOR1='rgba(174,197,212,0.7)'
#COLOR2='rgba(212,189,174,0.9)'

# brown and pale blue
#COLOR1='rgba(149,139,128,0.7)'
#COLOR2='rgba(127,137,148,0.9)'

# orange and grey
#COLOR1='rgba(255,245,198,0.7)'
#COLOR2='rgba(99,99,99,0.9)'

## subtle grey with a touch of brown ##
#COLOR1='rgba(174,197,212,0.7)'
#COLOR2='rgba(99,99,99,0.9)'

## subtle grey with a touch of brown ##
#COLOR1='rgba(234, 234, 234, 0.7)'
#COLOR2='rgba(99,99,99,0.9)'

## metallicy yellow
#COLOR1='rgba(255,245,198,0.7)'
#COLOR2='rgba(99,99,99,0.9)'

## just grey
#COLOR1='rgba(92, 136, 112, 0.7)'
#COLOR2='rgba(210, 211, 215, 0.9)'

# purple and tourquoisy green
COLOR1='rgba(153, 124, 171, 0.7)'
COLOR2='rgba(111, 175, 176, 0.9)'